### ISSUE TITLE
Issue: require() of ES modules is not supported.

### ISSUE THREAD

**Issue by zanecurrie** [eslint/eslintrc#73]
Came across this issue for "@eslint/eslintrc@1.2.0"
Using ESLint v2.2.2

_Failed to compile.

Must use import to load ES Module: /node_modules/@eslint/eslintrc/universal.js
require() of ES modules is not supported.
require() of /node_modules/@eslint/eslintrc/universal.js from /node_modules/eslint/lib/linter/linter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename universal.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/@eslint/eslintrc/package.json._

I realise it suggests removing the "type": "module" from the package.json but that seems extreme and problematic when dealing with automated build/deploy apps like Bamboo, etc. i.e. a build folder is deleted before every build starts.

Any chance of a fix for this in the source?
Cheers

**Comment by mdjermanovic** [comment]
> require() of /node_modules/@eslint/eslintrc/universal.js from /node_modules/eslint/lib/linter/linter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module"

It seems that `require("@eslint/eslintrc/universal")` resolves to `/node_modules/@eslint/eslintrc/universal.js` instead of  `/node_modules/@eslint/eslintrc/dist/eslintrc-universal.cjs`. I'd guess that you're using a Node version that doesn't support [package.exports](https://github.com/eslint/eslintrc/blob/67a7d5a6b96ecabf32d64242c1bc9cc016ab9bae/package.json#L7-L17) field.

Can you provide more details about your environment?

* Node version
* ESLint version (can you doublecheck, 2.2.2 is a very old version that doesn't use `@eslint/eslintrc`)
* How to reproduce this error (does this happen when you run ESLint from the command line?)

**Comment by zanecurrie** [comment]
Hi,
Using the following:

Node v12.16.1

VS Code ESLint extension v2.2.2

This issue was triggered when bumping versions as per GitHub Dependabot (npm install) & then compiling a React JS project that has Dev Dependencies:
"eslint-config-airbnb": "^17.1.1",
"eslint-plugin-chai-expect": "^2.2.0"

& "parser": "babel-eslint" in .eslintrc.json

As I said earlier adjusting the affected files, as per the suggestions in the node_modules is easy enough locally but problematic for CI/CD like Bamboo tasks that start with a clean build folder.

**Comment by aladdin-add** [comment]
hi, eslint v8 requires Node.js >= 12.22.0, please upgrade and retry.
